name: macos_build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: "macOS-10.15"
    steps:
        - uses: actions/checkout@v3
          with:
            submodules: recursive
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Build
          run: . build_macos_arm.sh
        - name: Upload release
          uses: yakuhzi/action-release@v1
          with:
            file: vscodium/VSCode-darwin-arm64/VSCodium.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
