name: macos_build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
  pull_request:
    branches: [ main ]
    
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Checkout submodules
          uses: textbook/git-checkout-submodule-action@master
  build:
    runs-on: "macOS-10.15"
    steps:
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Build
          run: . build_macos_arm.sh
    
